Description: Networking architecture

Parameters:
  VpcCidr:
    Description: CIDR block for the VPC
    Type: String
  PubSubnetACidr:
    Type: String
  PubSubnetBCidr:
    Type: String
  StudentName:
    Type: String

Resources:
# VPC
  MyTestVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      Tags:
        - Key: Name
          Value: !Sub "${StudentName}-vpc-week-14"

# PubSubnetA
  PubSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyTestVPC
      CidrBlock: !Ref PubSubnetACidr
      AvailabilityZone: "eu-west-2a"
      Tags:
        - Key: Name
          Value: !Sub "${StudentName}-week14-pub-subnet-A"

# PubSubnetB
  PubSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyTestVPC
      CidrBlock: !Ref PubSubnetBCidr
      AvailabilityZone: "eu-west-2a"
      Tags:
        - Key: Name
          Value: !Sub "${StudentName}-week14-pub-subnet-B"


  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${StudentName}-week14-igw"


  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref MyTestVPC
      InternetGatewayId: !Ref InternetGateway

  PubRouteA:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
      - Key: Name
        Value: !Sub "${StudentName}-week14-RouteTable-Pub-A"
      VpcId: !Ref MyTestVPC

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: InternetGateway
    Properties:
        RouteTableId: !Ref PubRouteA
        DestinationCidrBlock: 0.0.0.0/0
        GatewayId: !Ref InternetGateway

  PubSubnetRouteTableAssociationA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PubRouteA
      SubnetId: !Ref PubSubnetA

# # VPC Gateway Attachement

# # SubnetRouteTableAssociationA

# # Route Table Internet Gateway

# # Public Route

